#!/bin/bash

cp ~/.zshrc ~/.zshrc.backup

############
# Setup p10k
cat - ~/.zshrc.backup > ~/.zshrc <<EOF
# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "\${XDG_CACHE_HOME:-\$HOME/.cache}/p10k-instant-prompt-\${(%):-%n}.zsh" ]]; then
  source "\${XDG_CACHE_HOME:-\$HOME/.cache}/p10k-instant-prompt-\${(%):-%n}.zsh"
fi

EOF

sed -Ei 's|^ZSH_THEME="\w+"|ZSH_THEME="powerlevel10k/powerlevel10k"|' ~/.zshrc
sed -Ei 's|plugins=\(git\)|plugins=(git zsh-autosuggestions zsh-syntax-highlighting)|' ~/.zshrc

cat >> ~/.zshrc <<EOF

# To customize prompt, run \`p10k configure\` or edit ~/.p10k.zsh.
[[ ! -f /workspaces/project/.devcontainer/config/.p10k.zsh ]] \
	|| source /workspaces/project/.devcontainer/config/.p10k.zsh

HISTFILE=/command-history/.zsh-history
EOF

############
# Setup ASDF
cat >> ~/.zshrc <<EOF

. ~/.asdf/asdf.sh
EOF

if [[ -f ~/.gitconfig.host ]]; then
	cat ~/.gitconfig.host >> ~/.gitconfig
fi

# This helps with the delayed git status in the prompt.
(cd /workspaces/project && (git status &>/dev/null || true))
